name: deploy-pipeline
run-name: ${{ github.actor }} pushed
on:
  push:
    branches:    
      - main

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
        echo "A initial message"

      - run: echo "One last message"
