name: deploy-pipeline

on:
  push:
    branches:
      - main

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Initial Message
        run: echo "An initial message"

      - name: Print Last Message
        run: echo "One last message"
