name: deploy-pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Ensure correct title
        run: cat portfolio_page/index.html | grep "Experienced Developer"
